# Generated by Django 3.0.8 on 2020-07-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200703_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni - rocket', 'Foguete'), ('lni-laptop-phone', 'Responsivo'), ('lni-cog', 'Engrenagem'), ('lni-leaf', 'Design Moderno'), ('lni-layers', 'Multi Camadas'), ('lni-users', 'Contatos')], max_length=16, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Fearture',
                'verbose_name_plural': 'Featrues',
            },
        ),
    ]
